projects:
  portfolio:
    schemaPath: src/graphql/schema.json
    includes:
      - .ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: .
